# 1. 사라진 SQLException

## 

JdbcContext에서 JdbcTemplate으로 바꾸니까 예외들이 사라졌다?!?

```java
public void deleteAll() throws SQLException {
this.jdbcContext.executeSql("delete from users");
}
```

```java
public void deleteAll() {
this.jdbcTemplate.update("delete from users");
}
```

## 1.1 초난감 예외 처리

### 예외 블랙홀

```java
try {
...
}
catch(SQLException e) {
}
```

오류가 있어도 무시하고 계속 실행되게 된다.  화면에 오류를 출력해도 마찬가지다. 금방 묻히겠지..

```java
} catch (SQLException e) {
System.out.println(e);
}
```

```java
} catch (SQLException e) {
e.printStackTrace();
}
```

✨모든 예외는 적절하게 복구 되든지 아니면 작업을 중단 시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다. 
콘솔이나 로그에 예외 메시지를 출력할 바에 차라리 이게 낫다 .

```java
} catch (SQLException e) {
e.printStackTrace();
System.exit(1);
}
```

물론 이렇게 짜라는 말은 아니다. 예외 잡아서 조치할 방법이 없으면 차라리 밖으로 책임을 떠넘겨라. 

### 무의미하고 무책임한 throws

```java
public void method1() throws Exception {
method2();
...
}
public void method2() throws Exception {
method3();
...
}
public void method3() throws Exception {
...
}
```

## 1.2 예외의 종류와 특징

자바에서 throw를 통해 발생시킬 수 있는 예외 3가지

* Error

  * java.lang.Error 의 서브 클래스
  * 시스템에 뭔가 비정상적인 상황이 발생했을 경우 사용됨.
  * OutOfMemoryError, ThreadDeath etc
  * 주로  VM에서 던짐 ➡application code에서 잡으려고 하면 안된다.

* Exception 과 체크 예외

  * java.lang.Exception과 서브 클래스

  * 개발자들이 만든 application코드의 작업 중에 예외 상황이 발생했을 경우에 사용

  * Exception 클래스 종류

    * 체크 예외

      *  Exception의 서브 클래스
      * RuntimeException을 상속받지 않은 것
      * 예외를 처리하는 코드 반드시 작성

    * unchecked exception

      * RuntimException을 상속한 클래스
      * 예외처리 필수 아님
      * 프로그램의 오류가 있을 때 발생➡개발자 과실
      * NullPointerException, IllegalArgumentException etc

      > RuntimeException
      > Exception 의 서브 클래스

 ## 1.3 예외 처리 방법

### 예외 복구

예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓음.

Ex. 

사용자가 요청한 파일을 읽으려고 시도했는데 해당 파일이 없다거나 다른  문제가 있어서 읽히지가 않아서 IOException이 발생
➡사용자 에게 상황을 알려주고 다른 파일을 이용하도록 안내

단,  IOException 에러 메시지가 사용자에게 그냥 던져지는 것은 예외 복구라고 볼 수 없다.

예외가 처리됐으면 비록 사용자에게 예외 상황으로 비쳐도 application 안에서는 정상적으로 설계된 흐름을 따라가야 한다. 

 네트워크가 불안해서 가끔 서버에 접속이 잘 안 되는 열악한 환경에 있는 시스템이라 원격 DB 서버에 접속하다 실패해서 SQLException이 발생하는 경우➡ 재시도 혹은 일정 시간 대기했다가 다시 접속을 시도

```java
int maxretry = MAX_RETRY;
while(maxretry -- > 0) {
    try {
             ... 	 	 	 // 예외가 발생할 가능성이 있는 시도
             return;		 	 // 작업 성공
    }
    catch(SomeException e) {
             // 로그 출력. 정해진 시간만큼 대기
    }
    finally {
             // 리소스 반납. 정리 작업
    }
}
throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```

### 예외처리 회피

예외 처리 핸들링을 client에게 떠넘김.

```java
public void add() throws SQLException {
// JDBC API
}
```

```java
public void add() throws SQLException {
try {
 // JDBC API
}
catch(SQLException e) {
	 	 // 로그 출력
 throw e;
}
}
```

### 예외 전환

예외 회피와 마찬가지로 예외를 복구할 수 없어서 밖으로 던진다. 대신 그대로 던지는게 아니고 적절한 예외로 전환해서 던진다. 

두 가지 이유가 있다. 

1. 내부에서 발생한 예외를 그대로 던지는 것이 그 예외 상황에 대한 적절한 의미를 부여해주지 못할 때, 좀 더 의미를 분명히 할 예외로 바꿔서 던진다. 
   Ex.
   사용자 아이디 등록을 시도했을 떄 중복되서 JDBC api가 SQLException을 던지면 아이디를 등록하려던 서비스 계층 등에서는 왜  SQLException이 생겼는지 알길이 없다. ➡DAO에서 DuplicateException예외로 바꿔 던져야 서비스 계층에서 적절한 복구를 시도할 수 있다. 

   ```java
   public void add(User user) throws DuplicateUserIdException, SQLException {
       try {
                // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
                // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
       }
       catch(SQLException e) {
                // ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
        if (e.getErrorCode() = = MysqlErrorNumbers.ER_DUP_ENTRY) 
        throw DuplicateUserIdException();
        else 
        throw e; // 그 외의 경우는 SQLException 그대로
       }
   }
   ```

   😎보통 전환하는 예외에 원래 발생한 예외를 담아서 nested Exception으로 만드는게 좋다. getCause()로 처음 발생한 예외를 알 수 있어서다. 

   ```java
   catch(SQLException e) {
   ...
   throw DuplicateUserIdException(e);
   ```

2. 예외를 구체적으로 바꾸려는게 아닌, check exception을 unchecked exception으로 바꾸려고 할 때 사용한다.

```java
catch(SQLException e) {
...
throw DuplicateUserIdException().initCause(e); 
//➡이 경우 예외를 구체적으로 바꾸려는게 아닌, check exception을 unchecked exception으로 바꾸려고 할 때 사용한다. 
// 예를들어, 체크 예외인 EJB component 예외들은 은 의미있는 예외나 복구가능한 예외가 아니다. 고로 런타임 예외인 EJBException로 포장해서 던진다. 
try {
 OrderHome orderHome = EJBHomeFactory.getInstance().getOrderHome();
 Order order = orderHome.findByPrimaryKey(Integer id);
} catch (NamingException ne) {
 throw new EJBException(ne);
} catch (SQLException se) {
 throw new EJBException(se);
} catch (RemoteException re) {
 throw new EJBException(re);
}
    // EJB는 런타임 예외에서, 트랜잭션을 자동으로 롤백해준다. 
```



## 1.4 예외처리 전략

### 런타임 예외의 보편화

복구가능한 예외가 아니면 일단 언체크 예외로 만들어라. 
### Add()의 예외 처리

아이디가 중복될 때 사용할 DuplicateException을 런타임 예외로 만들자. 
중첩 예외로 쓸 수 있게  생성자 추가도 해주고

```java
package com.example.tobby.user.dao;

public class DuplicateUserIdException extends RuntimeException {
    public DuplicateUserIdException(Throwable cause) {
        super(cause);
    }
}

```

```java
public void add() throws DuplicateUserIdException {
    try {
             // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
             // 그런 기능이 있는 다른 SQLException을 던지는 메소드를 호출하는 코드
    }
    catch (SQLException e) {
     if (e.getErrorCode() = = MysqlErrorNumbers.ER_DUP_ENTRY) 
             throw new DuplicateUserIdException(e); 	 // 예외 전환
     else
             throw new RuntimeException(e);	 	 // 예외 포장
    }
}
```

😎런타임 예외를 쓰는 경우 컴파일러가 강제하지 않는 만큼 개발자가 더 신경 써야 한다. 

### application 예외

🤔지금까지, 일단 복구 할 수 있는 예외는 없다고 가정해서 죄다 런타임 예외로 돌려버리고, 시스템이 알아서 처리해주길 기대하지만 굳이 필요한 경우는 런타임 예외라도 잡아서 복구하겠다는 태도였다.
😎시스템 or 외부에서 예외가 발생한게 아니라 application 자체 로직에 의해 발생해버려 반드시 catch해줘야 하는 예외를 application 예외라고 한다. 

예를 들어

사용자가 요청한 금액을 출금하는 기능을 만드는데,
현재 잔고를 확인해서 범위를 넘어서면 출금을 중단시킨 후 적절한 경고를 보내야 한다. 설계 방식은 두 가지가 있다. 

1. 정상 출금 처리와 잔고 부족이 발생했을 때 각각 다른 종류의 리턴을 돌려준다.

   * 예외 상황과 리턴 값을 명확하게 코드화 하고 관리하지 않으면 혼란이 생긴다. 
   * if문으로 범벅

2. 정상적인 흐름을 따르는 코드는 그대로 두고 예외 상황에서는 비즈니스 의미를 가진 예외를 던진다. 

   * 의도적으로 체크 예외로 만든다. 

   * 예외 가능성이 있는 코드는 try에 모으고, 복구는 catch에 모아둘 수 있다. 

     ```java
     try {
     BigDecimal balance = account.withdraw(amount);
     ...
     	 // 정상적인 처리 결과를 출력하도록 진행
     }
     catch(InsufficientBalanceException e) {	 // 체크 예외
     	 // InsufficientBalanceException에 담긴 인출 가능한 잔고금액 정보를 가져옴
     BigDecimal availFunds = e.getAvailFunds();
     ...
     	 // 잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행
     }
     ```

### 1.5 SQLException은 어떻게 됐나?

그래서 JDBCTemplate은 throws SQLException이 왜 없나?
일단 SQLException은 코드 레벨에서 복구할 방법이 없다. 
원인이 주로..

* SQL 문법 에서
* 제약 조건 위반
* DB  server down
* nw 불안정
* DB connection pool full

가능한 빨리 런타임 예외로 전환해줘라. 그래서 JDBCTemplate은 이 전략을 따르고 있다. 

# 2. 예외 전환

## 2.1 JDBC 의 한계

JDBC는 DB가 바뀌어도 동일하게 개발할 수 있게 되었지만, 이렇게 DB종류를 초월한 데이터 접근 코드를 작성하는 일은 어렵다. 즉, DB를 자유롭게 바꾸기엔 JDBC가 해결하지 못하는 걸림돌이 두가지 있다. 

### 비표준 SQL

특정 DB만 가진 SQL은 결국 DAO코드에 들어가게 되고, DB에 종속적인 코드가 되버린다. 결국 DAO를 DB별로 만들어 사용하거나, SQL을 외부에서 독립시켜 바꿔쓸 수 있게 하는 수 밖에..

### 호환성 없는 SQLException의 DB error

DB마다 에러의 종류와 원인이 다르다. 고로 JDBC는 SQLException으로 퉁친다..
getErrorCode()로 에러 코드를 까서 원인을 파악해보려 해도  DB별로 에러 코드가 다르다. 

``` java
if (e.getErrorCode() = = MysqlErrorNumbers.ER_DUP_ENTRY) { ..
```

> SQLException 만으로 DB에 독립적인 유연한 코드를 작성하는 건 불가능에 가깝다.

## 2.2 DB에러 코드 매핑을 통한 전환

스프링은 DB별 에러 코드를 참고해서 발생한 예외의 원인이 무엇인지 해석해준다.

DB별 에러 코드 매핑 정보 테이블을 만들어두고 이를 이용한다. 

JdbcTemplate은 SQLException 을 런타임 예외인 DataSourceException의 서브 클래스들 중 적당한 것으로 포장해서 던진다. 

jdbcTemaplate을 사용하는 add()를 사용하는 쪽에서 중복 키 상황에 대응할 때 참고할 수 있도록  thorows DuplicateKeyException을 add()정의에 추가하자. 

```java
    public void add(User user) throws DuplicateKeyException {
        this.jdbcTemplate.update("insert into users (id, name, password) values(?,?,?)", user.getId(), user.getName(), user.getPassword());
    }
```

만약 체크 에러로 바꾸고 싶으면 이렇게 하면 되지.

```java
public void add() throws DuplicateUserIdException {
    try {
             // jdbcTemplate을 이용해 User를 add 하는 코드
    }
    catch(DuplicateKeyException e) {
             // 로그를 남기는 등의 필요한 작업
     throw new DuplicateUserIdException(e);
    }
}
```

 

## 2.3 DAO인터페이스와 DataAccessException계층 구조

 DataAccessException은 자바의 데이터 접근의 표준 기술(jdbc, jpa, jdo, iBatis, hibernate etc) 에서 발생하는  SQLException을 전환하는 용도로 사용된다. 
단, 데이터 액세스 기술의 종류와 상관없이 추상화된 예외로 제공한다. 

### DAO인터페이스와 구현의 분리

DAO는 인터페이스를 사용해 전략 패턴과 DI로 
구체적인 클래스의 정보와 구현 방법을 감추고,
DI를 통해 제공되도록 만든다.
하지만,, 메소드 선언에 나타나는 예외는 숨길 수 없다. 

```java
public void add(User user) throws SQLException; //jdbc api
public void add(User user) throws PersistentException; // JPA
public void add(User user) throws HibernateException; // Hibernate
public void add(User user) throws JdoException; // JDO
```

결국 인터페이스로 메소드의 구현은 추상화 했지만 구현 기술마다 던지는 예외가 다르기에 메소드의 선언이 달라진다. 즉 디비에 종속적이다. 

🤔모든 예외를 다 받아주는 throws Exception할까? 아냐 무책임해..

다행히도  JDO, Hibernate, JPA등은 SQLException 같은 체크 예외 대신 런타임 예외를 던져서 throws선언이 필요없다. 물론 SQLException을 던지는 Jdbc api는 런타임 예외로 포장하면 된다. 

하지만 충분하지 않다. 비즈니스 로직에서 의미있게 처리하거나, 시스템 레벨에서 의미있게 예외를 분류해야 하는 상황에서는 데이터 접근 기술에 따라 다른 예외가 던져지는 것이 여전히 해결되지 않는다. 

### 데이터 액세스 예외 추상화와 DataAccessException계층 구조

그래서 스프링은 자바의 다양한 데이터 접근 기술을 사용할 때 발생하는 예외들을 추상화해서 DataAccessException 계층구조 안에 정리해놓았다. 

## 2.4 기술에 독립적인 UserDao만들기

### 인터페이스 적용

UserDao를 인터페이스와 구현으로 분리해보자. 

```java
package com.example.tobby.user.dao;

import com.example.tobby.user.domain.User;

import java.util.List;

public interface UserDao {
    void add(User user);

    User get(String id);

    List<User> getAll();

    void deleteAll();

    int getCount();
}

```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
    <bean id="connectionMaker" class="com.example.tobby.user.dao.DConnectionMaker"/>
    <bean id="userDao" class="com.example.tobby.user.dao.UserDaoJdbc">
        <property name="dataSource" ref="dataSource"/>
    </bean>
    <bean id="dataSource" class="org.springframework.jdbc.datasource.SimpleDriverDataSource">
        <property name="driverClass" value="com.mysql.cj.jdbc.Driver"/>
        <property name="url" value="jdbc:mysql://localhost/tobby"/>
        <property name="username" value="tobaby"/>
        <property name="password" value="0000"/>
    </bean>
</beans>
```

보통 빈의 이름은 클래스 이름이 아니라,  dataSource 빈이 그랬던 것처럼 클래스의 구현 인터페이스 이름을 따르는 경우가 일반 적이다. 

```java
package com.example.tobby.user.dao;

import com.example.tobby.user.domain.User;
import org.springframework.jdbc.datasource.SimpleDriverDataSource;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

public class UserDaoJdbc implements UserDao {

    @Override
    public void add(User user) {

    }

    @Override
    public User get(String id) {
        return null;
    }

    @Override
    public List<User> getAll() {
        return null;
    }

    @Override
    public void deleteAll() {

    }

    @Override
    public int getCount() {
        return 0;
    }

    public void setDataSource(SimpleDriverDataSource dataSource) {
    }
}

```

### 테스트 보완

UserDaoTest에 중복된 키를 가진 정보를 등록했을 때 어떤 예외가 발생하는지를 확 인하기 위해 테스트를 하나 추가해보자

```java
    @Test
    public void duplicateKey() {
        assertThrows(DataAccessException.class, () -> {
            dao.deleteAll();
            dao.add(user1);
            dao.add(user1);
        });
    }
```

스무스하게 통과되는데 구체적으로 어떤 예외인지 궁금하니까 assertThrows를 잠시 주석처리하니 뱉는 에러가 말하기를 DuplicateKeyException이라고 한다. 

```java
    @Test
    public void duplicateKey() {
        assertThrows(DuplicateKeyException.class, () -> {
            dao.deleteAll();
            dao.add(user1);
            dao.add(user1);
        });
    }
```

### DataAccessException 활용시 주의사항

예외 코드를 보고 DuplicateKeyException 을 던지는 JDBC와 달리 hibernate나 jpa는 각자가 정의한 예외를 던지기 때문에 추상화된 공통 예외로 정의할 때 실제로 전환되는 예외의 종류를 체크해놔야 한다. 

스프링은  SQLException을 해석해 DataAccessException으로 변환하는 다양한 방법을 제공하는데
제일 흔한게 DB에러 코드를 이용하는 것이다. SQLExceptionTranslator의 구현체 중, SQLErrorCodeSQLExceptionTranslator를 쓰면 된다. 

``` java
  @Autowired
    DataSource dataSource;

    @Test
    public void sqlExceptionTranslate() {
        dao.deleteAll();
        try {
            dao.add(user1);
            dao.add(user1);
        } catch (DuplicateKeyException e) {
            SQLException sqlEx = (SQLException)e.getRootCause();
            SQLExceptionTranslator set =
                    new SQLErrorCodeSQLExceptionTranslator(this.dataSource);
            assertThat(set.translate(null, null, sqlEx)).isInstanceOf(DuplicateKeyException.class);
        }
    }
```

